### PR TITLE
Add missing destructuring to createBox statement in readme

### PR DESCRIPTION
**Pull request by Seam7**

### CODE REVIEW

**Comment by TheMightyPenguin** [comment]
Thanks for the contribution!! 🎉🎉💯

**Review by TheMightyPenguin — APPROVED** [review]
💯✅

**Comment by jose-landero** [comment]
@TheMightyPenguin Sorry for the comment on a merged PR, but I think that the return of `createBox` doesn't need to be destructured

**Comment by TheMightyPenguin** [comment]
> @TheMightyPenguin Sorry for the comment on a merged PR, but I think that the return of `createBox` doesn't need to be destructured

Hey @jose-landero ! It actually needed to be on a previous version as we actually returned an object, but not anymore, we refactored to the old API yesterday. But this was needed as we were actually returning an object!

**Comment by jose-landero** [comment]
Oh! I see, that's why I get confused 😅  Thanks, awesome work!

**Comment by TheMightyPenguin** [comment]
> Oh! I see, that's why I get confused 😅 Thanks, awesome work!

@jose-landero thank you haha it makes me happy to see people using this project and looking around in the repository! 🙌

**Pull request merged**
